config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :task_categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id               :bigint           not null, primary key
#  name             :string
#  description      :text
#  due_date         :date
#  task_category_id :bigint           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Task < ApplicationRecord
  belongs_to :task_category
end

app/models/task_category.rb
# == Schema Information
#
# Table name: task_categories
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class TaskCategory < ApplicationRecord
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_local

  private

  def set_local
    I18n.locale = 'es'
  end

end

app/controllers/task_categories_controller.rb
class TaskCategoriesController < ApplicationController
  before_action :set_task_category, only: [:show, :edit, :update, :destroy]

  # GET /task_categories
  # GET /task_categories.json
  def index
    @task_categories = TaskCategory.all
  end

  # GET /task_categories/1
  # GET /task_categories/1.json
  def show
  end

  # GET /task_categories/new
  def new
    @task_category = TaskCategory.new
  end

  # GET /task_categories/1/edit
  def edit
  end

  # POST /task_categories
  # POST /task_categories.json
  def create
    @task_category = TaskCategory.new(task_category_params)

    respond_to do |format|
      if @task_category.save
        format.html { redirect_to @task_category, notice: 'Task category was successfully created.' }
        format.json { render :show, status: :created, location: @task_category }
      else
        format.html { render :new }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_categories/1
  # PATCH/PUT /task_categories/1.json
  def update
    respond_to do |format|
      if @task_category.update(task_category_params)
        format.html { redirect_to @task_category, notice: 'Task category was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_category }
      else
        format.html { render :edit }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_categories/1
  # DELETE /task_categories/1.json
  def destroy
    @task_category.destroy
    respond_to do |format|
      format.html { redirect_to task_categories_url, notice: 'Task category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_category
      @task_category = TaskCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_category_params
      params.require(:task_category).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :due_date, :task_category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_categories_helper.rb
module TaskCategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskOrganizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task_categories/_form.html.erb
<%= simple_form_for(@task_category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: t('.name') %>
    <%= f.input :description, label: t('.description')%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/task_categories/edit.html.erb
<h1>Editing Task Category</h1>

<%= render 'form', task_category: @task_category %>

<%= link_to 'Show', @task_category %> |
<%= link_to 'Back', task_categories_path %>

app/views/task_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_categories.each do |task_category| %>
      <tr>
        <td><%= task_category.name %></td>
        <td><%= task_category.description %></td>
        <td><%= link_to 'Show', task_category %></td>
        <td><%= link_to 'Edit', edit_task_category_path(task_category) %></td>
        <td><%= link_to 'Destroy', task_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Category', new_task_category_path %>

app/views/task_categories/new.html.erb
<h1><%= t('task_categories.new_category') %></h1>

<%= render 'form', task_category: @task_category %>

<%= link_to t('common.back'), task_categories_path %>

app/views/task_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_category.description %>
</p>

<%= link_to 'Edit', edit_task_category_path(@task_category) %> |
<%= link_to 'Back', task_categories_path %>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :due_date %>
    <%= f.association :task_category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Due date</th>
      <th>Task category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= task.task_category_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Task category:</strong>
  <%= @task.task_category_id %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>